export const products = [
    {
        _id: 1,
        name: "Product 1",
        image: "../images/one.jpg",
        description: "product one description",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: 2,
        name: "Product 2",
        image: "../images/product-2.jpg",
        description: "product two description",
        brand: "Microsoft",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: 3,
        name: "Product 3",
        image: "../images/product-3.jpg",
        description: "product three description",
        brand: "Google",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: 4,
        name: "Product 1",
        image: "../images/product-4.jpg",
        description: "product Four description",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: 5,
        name: "Product 5",
        image: "../images/product-2.jpg",
        description: "product five description",
        brand: "Microsoft",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: 6,
        name: "Product 6",
        image: "../images/product-3.jpg",
        description: "product six description",
        brand: "Google",
        category: "Electronics",
        price: 89.99,
        countInStock: 5,
        rating: 4.8,
        numReviews: 3,
    },
];
